### PR TITLE
Incorporate uv

### PR DESCRIPTION
**Pull request by Yuan-Ru-Lin**
Implement #2.

With this PR, one can run a simple pipeline as follows.

```bash
# Make sure you have uv installed
git clone https://github.com/legend-exp/legend-dataflow-hades
cd legend-dataflow-hades
uv sync

# Make sure you are on NERSC
mkdir -p generated/tier/daq/V04545A/th_HS2_top_psa/
cd generated/tier/daq/V04545A/th_HS2_top_psa/
ln -s /global/cfs/cdirs/m2676/data/teststands/hades/char_data/V04545A/tier0/th_HS2_top_psa/char_data-V04545A-th_HS2_top_psa-run0001-200824T121112.fcio .
cd -
snakemake all-char_data-V04545A-th_HS2_top_psa-raw.gen
```

P.S. there are other changes made by George in his directory in LNGS when I copied the whole thing before I started this study.

### CODE REVIEW

**Comment by Yuan-Ru-Lin** [comment]
I still need to figure out what's going on in `inputs/dataprod/config/`

**Comment by Yuan-Ru-Lin** [comment]
Hi @ggmarshall, can you help me understand the change you made to `inputs/dataprod/config/`.

Here is my understanding. `inputs/` is a local copy of `legend-exp/legend-metadata` and `inputs/dataprod/config/` should be a local copy of `legend-exp/legend-dataflow-config`, but you changed to be `ggmarshall/hades-dataflow-config` to let the workflow know how to deal with the HADES data.

**Comment by ggmarshall** [comment]
I think we'll need a separate set of configs for Hades data as the scripts may need different options / we may be running different scripts to the legend dataflow, we should think how to handle this and where we might want it to fit in with the legend-metadata as would be nice to have e.g. the detector database cloned for hades processing even if some of the other parts aren't relevant. I can speak to Oli about making a legend-exp `hades-dataflow-config`

**Comment by Yuan-Ru-Lin** [comment]
Let's deal with the configuration later. Let me merge this PR so that I can add ruff in #5.

**Pull request merged**
